### ISSUE TITLE
Error Fatal

### ISSUE THREAD

**Issue by socramjunio2** [nikapps/ortc-laravel#6]
Good evening, I'm using your laravel package and is working almost everything perfectly, but I am having a strange error that says not find the service provider's file, the strange thing is that I can not use it without taking a composer update -o and other artisan commands are giving errors for work necessary to remove the file autoload classname config / app.php ..

follows a ss:
http://prntscr.com/caldd8

**Comment by alibo** [comment]
Hi, thanks :)
Could you please upload it somewhere else? It gives me a 502 error.
(You can also upload it here :) )

**Comment by socramjunio2** [comment]
![0da499d5d45b4bbca606bd0cde8b4b5e](https://cloud.githubusercontent.com/assets/21258161/18028036/fed3fc9c-6c49-11e6-9167-df4b2e05c325.png)

Follow the picture, thank you.

**Comment by alibo** [comment]
May you post your `composer.json` file? :)

**Comment by socramjunio2** [comment]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2._",
        "nesbot/carbon": "^1.21",
        "doctrine/dbal": "^2.5",
        "s-ichikawa/laravel-sendgrid-driver": "dev-master",
        "vinkla/pusher": "^2.3",
        "laravolt/avatar": "^1.4",
        "arcanedev/gravatar": "^1.2",
        "webpatser/laravel-uuid": "2._",
        "cviebrock/eloquent-sluggable": "^4.0.2",
        "yajra/laravel-datatables-oracle": "~6.0",
        "webwizo/laravel-shortcodes": "1.0._",
        "laravelcollective/html": "5.2._",
        "intervention/image": "^2.3",
        "bican/roles": "2.1._",
        "highideas/laravel-users-online": "^1.0",
        "kennedytedesco/validation": "~3.0",
        "rutorika/sortable": "^3.2",
        "aws/aws-sdk-php": "~3.0",
        "pda/pheanstalk": "^3.1",
        "predis/predis": "^1.1",
        "pusher/pusher-php-server": "^2.4",
        "nikapps/ortc-php": "1._",
        "nikapps/ortc-laravel": "^2.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8._|3.0._",
        "symfony/dom-crawler": "2.8._|3.0.*",
        "barryvdh/laravel-ide-helper": "^2.2"
    },
    "autoload": {
        "classmap": [
            "database",
            "lib/Pagarme"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\Foundation\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\Foundation\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by alibo** [comment]
Long list :D

I tested myself and it works for me :)

May you try it with a plain Laravel 5.2.x project?

```
composer create-project laravel/laravel:5.2.* laravel-ortc-project
```

Also, please make sure your composer is up to date :)

**Comment by socramjunio2** [comment]
After installation you tried to take a composer update?

**Comment by alibo** [comment]
@socramjunio2 You're right. It's weird.
When you run `dump-autoload -o`, Composer also creates static entries for each file. 

I'm working on it now.
I will notify you :)

**Comment by alibo** [comment]
@socramjunio2 
When I migrated this package from psr-0 to psr-4, I forgot to change directory structures.
It seems I have to work on a major release!! :D (specially for Laravel 5.3)

Btw, I've fixed it. please test it again. (https://github.com/nikapps/ortc-laravel/releases/tag/2.0.3)

```
➜  laravel-ortc-project composer update
    1/1:        http://packagist.org/p/provider-latest$aa341f4724d211db18403f84c07d47189c0f85c4544572e6d77784b8f76ef387.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:        https://codeload.github.com/nikapps/ortc-laravel/legacy.zip/b1a1befb33520d66fdaebf2fa14e278fba5ce3f3
    Finished: success: 1, skipped: 0, failure: 0, total: 1
  - Removing nikapps/ortc-laravel (2.0.2)
  - Installing nikapps/ortc-laravel (2.0.3)
    Loading from cache

Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.
Writing lock file
Generating autoload files
Class Illuminate\Foundation\ComposerScripts is not autoloadable, can not call post-update-cmd script
> php artisan optimize
Generating optimized class loader

➜  laravel-ortc-project tinker
Psy Shell v0.6.1 (PHP 7.0.10 — cli) by Justin Hileman
>>>
```

Thanks 👍

**Comment by socramjunio2** [comment]
Thanks @alibo
